#!/bin/bash
# TaskFlow Lite - Demo Account Setup
# This script creates demo accounts with test data for demonstration purposes

# Demo User Credentials (for manual testing via UI)
# You can register these accounts through the app interface

echo "=========================================="
echo "TaskFlow Lite - Demo Setup Guide"
echo "=========================================="
echo ""
echo "🎯 DEMO ACCOUNTS FOR MANUAL TESTING"
echo "=========================================="
echo ""
echo "You can register these accounts through the app's registration page:"
echo ""
echo "Account 1 (Product Lead):"
echo "  Email:    alice@taskflow.demo"
echo "  Password: Demo@123"
echo "  Role:     Team Leader"
echo ""
echo "Account 2 (Developer):"
echo "  Email:    bob@taskflow.demo"
echo "  Password: Demo@123"
echo "  Role:     Team Member"
echo ""
echo "Account 3 (Developer):"
echo "  Email:    charlie@taskflow.demo"
echo "  Password: Demo@123"
echo "  Role:     Team Member"
echo ""
echo "Account 4 (Marketing Lead):"
echo "  Email:    diana@taskflow.demo"
echo "  Password: Demo@123"
echo "  Role:     Team Leader"
echo ""
echo "Account 5 (Admin):"
echo "  Email:    eve@taskflow.demo"
echo "  Password: Demo@123"
echo "  Role:     Admin"
echo ""
echo "=========================================="
echo "🗄️  DATABASE DEMO DATA"
echo "=========================================="
echo ""
echo "To populate the database with demo data:"
echo ""
echo "1. Open PostgreSQL:"
echo "   psql -U postgres -d taskflow_lite"
echo ""
echo "2. Run the demo session:"
echo "   \\i task-flow-lite.session.sql"
echo ""
echo "3. Or run via command line:"
echo "   psql -U postgres -d taskflow_lite -f task-flow-lite.session.sql"
echo ""
echo "=========================================="
echo "📋 DEMO DATA INCLUDES:"
echo "=========================================="
echo ""
echo "✅ 5 Demo Users (different roles)"
echo "✅ 3 Demo Teams (Product, Marketing, Design)"
echo "✅ 11 Demo Tasks (various statuses/priorities)"
echo "✅ 13 Activity Logs (showing task lifecycle)"
echo ""
echo "The demo data uses IDs ending with '_demo' for easy identification."
echo ""
echo "=========================================="
echo "🎬 SUGGESTED DEMO FLOW"
echo "=========================================="
echo ""
echo "1. Register Account:"
echo "   - Use alice@taskflow.demo as the Product Lead"
echo "   - This auto-creates your first user in the database"
echo ""
echo "2. Create a Team:"
echo "   - Team Name: Product Development"
echo "   - Description: Building awesome features"
echo ""
echo "3. Add Team Members:"
echo "   - Click 'Add Member' and enter another user's ID"
echo "   - Invite bob and charlie to the team"
echo ""
echo "4. Create Tasks:"
echo "   - Add tasks with different priorities/statuses"
echo "   - Assign them to team members"
echo "   - Update their status as they progress"
echo ""
echo "5. View Analytics:"
echo "   - See team overview with task statistics"
echo "   - Check completion rate"
echo "   - View tasks per user breakdown"
echo ""
echo "6. Review Activity Log:"
echo "   - See all team and task changes"
echo "   - Track who did what and when"
echo ""
echo "=========================================="
echo "💡 QUICK START"
echo "=========================================="
echo ""
echo "1. Make sure database migrations are done:"
echo "   cd server"
echo "   npm run migrate"
echo ""
echo "2. Load demo data (optional):"
echo "   psql -U postgres -d taskflow_lite -f task-flow-lite.session.sql"
echo ""
echo "3. Start the app:"
echo "   cd server && npm run dev"
echo "   cd client && npm run dev"
echo ""
echo "4. Register first demo account:"
echo "   - Go to http://localhost:5173/register"
echo "   - Use alice@taskflow.demo and any password"
echo ""
echo "5. Login and explore!"
echo ""
echo "=========================================="
echo ""
